name: webeoapp
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  cupertino_icons: ^0.1.3

  # Translations
  intl: ^0.16.1
  intl_translation: ^0.17.9

  # state management
  stacked: ^1.6.0
  stacked_hooks: ^0.1.2
  flutter_hooks: ^0.9.0
  # navigation
  auto_route:
  stacked_services: ^0.4.4+1
  # Inversion of control
  get_it:
  injectable:
  # Google Sign in
  firebase_auth: ^0.16.1
  google_sign_in: ^4.5.1
  # Api
  dio: ^3.0.8
  dio_cookie_manager: ^1.0.0
  # Streaming
  jitsi_meet: ^0.2.5
  
  morpheus: ^1.2.2+1
  connectivity: ^0.4.6+2
  toast: ^0.1.5
  path_provider: ^1.5.1
  retry: ^3.0.0+1
  auto_size_text: ^2.1.0
  overlay_support: ^1.0.2
  dbcrypt: ^1.0.0
  esys_flutter_share: ^1.0.2
  shared_preferences: ^0.5.7
  package_info: ^0.4.0+13
  url_launcher: ^5.4.1
  permission_handler: '^4.2.0+hotfix.3'
  liquid_pull_to_refresh: ^1.1.1
  line_icons: ^0.2.0
  flutter_svg: ^0.17.4
  google_fonts: ^1.1.0
  font_awesome_flutter: ^8.7.0
  charts_flutter: ^0.9.0
  cached_network_image: ^2.2.0+1
  pie_chart: ^3.1.1
  flutter_swiper: ^1.1.6
  json_annotation: ^3.0.1
  flutter_secure_storage: ^3.3.1+1
  animations: ^1.0.0+5
  crypto: ^2.1.3
  time_range_picker : any
  image_picker: ^0.6.7+2
  google_maps_place_picker: ^0.9.4
  flutter_native_image: ^0.0.5+2
  flutter_exif_rotation: ^0.2.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  build_runner:
  auto_route_generator:
  injectable_generator:

flutter:

  uses-material-design: true
  assets:
    - assets/social/